# Generated by Django 5.1 on 2024-08-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_factura_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Pelotas', 'Pelotas'), ('Accesorios', 'Accesorios'), ('Calzado', 'Calzado'), ('Chaquetas', 'Chaquetas'), ('Bolsas', 'Bolsas'), ('Guantes', 'Guantes'), ('Cinturones', 'Cinturones'), ('Mochilas', 'Mochilas'), ('Sudaderas', 'Sudaderas'), ('Rodilleras', 'Rodilleras'), ('Casco', 'Casco'), ('Elásticos', 'Elásticos'), ('Stick', 'Stick')], max_length=50),
        ),
    ]
