# Generated by Django 5.1 on 2024-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0011_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Remeras', 'Remeras'), ('Botines', 'Botines'), ('Calzado', 'Calzado'), ('Pantalones', 'Pantalones'), ('Rodilleras', 'Rodilleras'), ('Zapatillas', 'Zapatillas'), ('Campos', 'Campos'), ('Chalecos', 'Chalecos'), ('Gorras', 'Gorras'), ('Guantes', 'Guantes'), ('Mochilas', 'Mochilas'), ('Toallas', 'Toallas'), ('Cinturones', 'Cinturones'), ('Bandas elásticas', 'Bandas elásticas'), ('Calcetines', 'Calcetines'), ('Pantalones cortos', 'Pantalones cortos'), ('Protectores', 'Protectores'), ('Pelotas', 'Pelotas'), ('Kit entrenamiento', 'Kit entrenamiento'), ('otro', 'otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Reebok', 'Reebok'), ('Under Armour', 'Under Armour'), ('New Balance', 'New Balance'), ('Asics', 'Asics'), ('Mizuno', 'Mizuno'), ('Wilson', 'Wilson'), ('Converse', 'Converse'), ('Fila', 'Fila'), ('Skechers', 'Skechers'), ('Champion', 'Champion'), ('Saucony', 'Saucony'), ('Brooks', 'Brooks'), ('Kappa', 'Kappa'), ('Vans', 'Vans'), ('Lotto', 'Lotto'), ('Columbia', 'Columbia'), ('Oakley', 'Oakley'), ('Hummel', 'Hummel'), ('Trekking', 'Trekking'), ('Joma', 'Joma'), ('Karhu', 'Karhu'), ('Hoka One One', 'Hoka One One'), ('Palladium', 'Palladium'), ('otro', 'otro')], max_length=50),
        ),
    ]
