# Generated by Django 5.1 on 2024-08-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
