# Generated by Django 5.1 on 2024-08-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Calzado', 'Calzado'), ('Accesorios', 'Accesorios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Unisex', 'Unisex'), ('null', None)], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=50),
        ),
    ]
