# Generated by Django 5.0.6 on 2024-08-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_remove_detallecompra_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
    ]
